
# Task name - used to pick the class to load
task_name: ${task.name}
teacher_mode: False
pc_input: True
#shape 
shape: ""
# if set to positive integer, overrides the default number of environments
num_envs: 4096
# seed - set to -1 to choose random seed
seed: 0
# set to True for deterministic performance
torch_deterministic: False

# set the maximum number of learning iterations to train for. overrides default per-environment setting
max_iterations: ''

## Device config
#  'physx' or 'flex'
physics_engine: 'physx'
# whether to use cpu or gpu pipeline
pipeline: 'cpu'
num_gpus: 1 # if 1, it will only use the gpu indicated below. Otherwise it will use num_gpus in order starting from zero (ignoring the gpu config below)
# device for running physics simulation
sim_device: 'cpu'
# device to run RL
rl_device: 'cpu'
graphics_device_id: 0

## PhysX arguments
num_threads: 4 # Number of worker threads per scene used by PhysX - for CPU PhysX only.
solver_type: 1 # 0: pgs, 1: tgs
num_subscenes: 4 # Splits the simulation into N physics scenes and runs each one in a separate thread


# RLGames Arguments
# test - if set, run policy in inference mode (requires setting checkpoint to load)
test: False
track_pose: False 
get_target_reference: False
get_target_traj: False  
# save_jit - if Yes, it will save the Jit for execution on a real robot
save_jit: False
# used to set checkpoint path
checkpoint: ''
dagger_checkpoint: ''
# set sigma when restoring network
sigma: ''
# set to True to use multi-gpu training
multi_gpu: False

wandb_activate: False
wandb_group: ''
wandb_name: AllegroKukaGraspingTest
wandb_entity: 'himanshu_singh'
wandb_project: 'isaacgym'
wandb_tags: []
wandb_logcode_dir: '' 

capture_video: False
capture_video_freq: 1464
capture_video_len: 100
force_render: True

# disables rendering
headless: True

# set default task and default training config based on task
defaults:
  - _self_
  - task: AllegroXarmNew
  - train: ${task}PPO
  - pretrain: ${task}

# set the directory where the output files get saved
hydra:
  output_subdir: null
  run:
    dir: .
